<a href="https://colab.research.google.com/github/AbhinavKumar07/C123V2/blob/main/C_123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import random

rewards = np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,-1,-1],
    [0,-1,-1,-1,-1,100],
    [-1,-1,-1,-1,0,100]
])



In [11]:
def set_initial_state():
  return np.random.randint(0,6)

set_initial_state()

2

In [12]:
def get_action(current_state , reward_matrix):
  available_action = []
  print("Reward_matrix","\n" , reward_matrix)

  for action in enumerate(reward_matrix[current_state]):
    if action[1] != -1 :
      available_action.append(action[0])

  choose_action = random.choice(available_action)
  print("Random choice of action from" , available_action , "is" , choose_action)
  return choose_action

In [13]:
current_state = 3
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [1, 2] is 2
2


In [14]:
current_state = 4
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [0, 5] is 0
0


In [15]:
current_state = 5
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4, 5] is 5
5


In [16]:
current_state = 0
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4] is 4
4


In [17]:
current_state = 1
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [3, 5] is 5
5


In [18]:
current_state = 2
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [3] is 3
3
